/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("org.hibernate:hibernate-core:6.5.0.CR1")  // Replace with the latest version
    implementation("org.hibernate:hibernate-entitymanager:5.4.24.Final")  // Replace with the latest version
    implementation("org.postgresql:postgresql:42.7.3")  // Replace with the latest version
    implementation("javax.persistence:javax.persistence-api:2.2")
    implementation("commons-io:commons-io:2.16.1")
    // Other dependencies as needed
    

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.tutorial.hibernate.postgresql.demo"
}
